Add remaining files for replay1 'test'

diff --git a/tests/replay1/Makefile b/tests/replay1/Makefile
--- a/tests/replay1/Makefile
+++ b/tests/replay1/Makefile
@@ -1,4 +1,11 @@
 include ../Makefile.boilerplate
 
 $(TEST):
-	@../../utils/edit_server_driver.py replay1.txt $(PWD) output
+	@../../utils/edit_server_driver.py replay1.txt $(PWD) buffer > output
+	@diff output expected > /dev/null ; \
+	if [ $$? -ne 0 ] ; then \
+		echo "Failed" ; \
+		exit 1 ; \
+	else \
+		echo "Ok" ; \
+	fi
