Add markers and Makefile rules to ensure token sections are identical

diff --git a/src/Makefile.common b/src/Makefile.common
--- a/src/Makefile.common
+++ b/src/Makefile.common
@@ -33,6 +33,29 @@ yacc_parser.tab.c: yacc_parser.y $(YACC)
 cexp_parser.tab.c: cexp_parser.y $(YACC)
 	$(YACC) -v -b cexp_parser -p cexpyy cexp_parser.y
 
+# Check that the token definitions in the grammars are exactly the same
+c_parser.tokens: c_parser.y
+	cat c_parser.y | sed -E '/END OF COMMON TOKEN DEFINITIONS/,$$d' | sed -E '0,/START OF COMMON TOKEN/d' > c_parser.tokens
+
+yacc_parser.tokens: yacc_parser.y
+	cat yacc_parser.y | sed -E '/END OF COMMON TOKEN DEFINITIONS/,$$d' | sed -E '0,/START OF COMMON TOKEN/d' > yacc_parser.tokens
+
+java_parser.tokens: java_parser.y
+	cat java_parser.y | sed -E '/END OF COMMON TOKEN DEFINITIONS/,$$d' | sed -E '0,/START OF COMMON TOKEN/d' > java_parser.tokens
+
+check-tokens: c_parser.tokens yacc_parser.tokens java_parser.tokens
+	@if ! diff -q c_parser.tokens yacc_parser.tokens ; then \
+		echo "ERROR: Parser token definition section mismatch:" ; \
+		diff -c c_parser.tokens yacc_parser.tokens ; \
+	fi
+	@if ! diff -q yacc_parser.tokens java_parser.tokens ; then \
+		echo "ERROR: Parser token definition section mismatch:" ; \
+		diff -c yacc_parser.tokens java_parser.tokens ; \
+	fi
+	@if ! diff -q java_parser.tokens c_parser.tokens ; then \
+		echo "ERROR: Parser token definition section mismatch:" ; \
+		diff -c java_parser.tokens c_parser.tokens ; \
+	fi
 
 #########################################################################
 # Once we have a compiled c-xref we can regenerate the enum string
@@ -63,6 +86,7 @@ enumTxt:
 c-xref: .c-xrefrc $(OBJS)
 	$(CC) $(LDFLAGS) -o c-xref $(OBJS) $(LIBS)
 	@make enumTxt
+	@make check-tokens
 
 .c-xrefrc: c-xrefrc.tpl
 	@sed -e "s+CURDIR+$(CURDIR)+g" c-xrefrc.tpl > .c-xrefrc
